using Fantastic3D.Persistence.Entities;
using AutoFixture;
using Fantastic3D.DataManager;

namespace Fantastic3D.Persistence
{
    /// <summary>
    /// Dummy Data generation for quick testing. Should not be used in the final project.
    /// </summary>
    public class DummyDataHandler<T> : IDataHandler<T> where T : IManageable
    {

        public void LoadData(List<T> loadedList)
        {
            switch (loadedList)
            {
                case List<TagTypeEntity> tagTypeList:
                    tagTypeList.AddRange(new List<TagTypeEntity>()
                    {
                        new TagTypeEntity("Format", false, isOnlyOne:true),
                        new TagTypeEntity("Licence", false, isOnlyOne:true),
                        new TagTypeEntity("Thématique", true, false),
                        new TagTypeEntity("Catégories", true, false),
                        new TagTypeEntity("Style", false, false),
                        new TagTypeEntity("Capacités", false, false),
                    });
                    break;
                case List<TagEntity> tagList:
                    tagList.AddRange(new List<TagEntity>()
                    {
                        new TagEntity("FBX", 1),
                        new TagEntity("3DS", 1),
                        new TagEntity("OBJ", 1),
                        new TagEntity("Max", 1),
                        new TagEntity("X3D", 1),
                        new TagEntity("STL", 1),
                        new TagEntity("Usage personnel", 2),
                        new TagEntity("Usage commercial", 2),
                        new TagEntity("Libre de droits", 2),
                        new TagEntity("Futuriste", 3),
                        new TagEntity("Moderne", 3),
                        new TagEntity("Médiéval", 3),
                        new TagEntity("Horreur", 3),
                        new TagEntity("Fantasie", 3),
                        new TagEntity("Personnage", 4),
                        new TagEntity("Animal", 4),
                        new TagEntity("Monstre", 4),
                        new TagEntity("Décor", 4),
                        new TagEntity("Végétation", 4),
                        new TagEntity("Véhicule", 4),
                        new TagEntity("Machine", 4),
                        new TagEntity("Arme", 4),
                        new TagEntity("Low-Poly", 5),
                        new TagEntity("Réaliste", 5),
                        new TagEntity("Toon", 5),
                        new TagEntity("Texture", 6),
                        new TagEntity("Rigging", 6),
                        new TagEntity("Animation", 6),
                    });
                    break;
                case List<AssetEntity> assetsList:
                    //var tagList = new List<TagEntity>();
                    //var fakeUser = new UserEntity(1, "fakeuser", "Fake", "User", "fake.user@dontmind.me", "foobar", "1 avenue de la Data, Dropville", UserRole.Premium);
                    assetsList.AddRange(new List<AssetEntity>()
                    {
                        new AssetEntity("Puffin lowPoly", "A low-poly puffin. How convenient!", 0f, "puffin.fbx", "atlantic-puffin-2.jpg", 1),
                        new AssetEntity("Haunted castle", "A haunted castle. How scary!", 0f, "castle.3ds", "castle.jpg", 1),
                        new AssetEntity("Saxophone", "A musical instrument called saxophone. How jazzy!", 0f, "sax.fbx", "sax.jpg", 1),
                        new AssetEntity("Snake western patch-nosed","empower out-of-the-box niches",14.95f,"snake western patch-nosed.fbx","snake western patch-nosed.png",45),
                        new AssetEntity("Snake green vine", "benchmark B2B e-markets", 14.95f, "snake green vine.fbx", "snake green vine.png", 66),
                        new AssetEntity("White-throated monitor", "architect holistic eyeballs", 9.95f, "white-throated monitor.fbx", "white-throated monitor.png", 93),
                        new AssetEntity("Cobra egyptian", "scale open-source technologies", 4.95f, "cobra egyptian.fbx", "cobra egyptian.png", 47),
                        new AssetEntity("Long-tailed spotted cat", "maximize user-centric vortals", 0f, "long-tailed spotted cat.fbx", "long-tailed spotted cat.png", 8),
                        new AssetEntity("Common green iguana", "orchestrate distributed infomediaries", 4.95f, "common green iguana.fbx", "common green iguana.png", 100),
                        new AssetEntity("Snake green vine", "facilitate efficient e-tailers", 14.95f, "snake green vine.fbx", "snake green vine.png", 17),
                        new AssetEntity("Black-fronted bulbul", "reintermediate dynamic convergence", 9.95f, "black-fronted bulbul.fbx", "black-fronted bulbul.png", 68),
                        new AssetEntity("Squirrel golden-mantled ground", "reintermediate bricks-and-clicks ROI", 14.95f, "squirrel golden-mantled ground.fbx", "squirrel golden-mantled ground.png", 95),
                        new AssetEntity("Stork painted", "mesh B2B e-commerce", 0f, "stork painted.fbx", "stork painted.png", 88),
                        new AssetEntity("Eagle tawny", "integrate distributed architectures", 4.95f, "eagle tawny.fbx", "eagle tawny.png", 4),
                        new AssetEntity("Cook's tree boa", "implement bleeding-edge relationships", 9.95f, "cook's tree boa.fbx", "cook's tree boa.png", 11),
                        new AssetEntity("Macaw scarlet", "exploit plug-and-play networks", 9.95f, "macaw scarlet.fbx", "macaw scarlet.png", 15),
                        new AssetEntity("Black-backed magpie", "reinvent frictionless communities", 14.95f, "black-backed magpie.fbx", "black-backed magpie.png", 45),
                        new AssetEntity("Pelican brown", "facilitate e-business e-commerce", 14.95f, "pelican brown.fbx", "pelican brown.png", 57),
                        new AssetEntity("Lizard (unidentified)", "deliver viral infrastructures", 4.95f, "lizard (unidentified).fbx", "lizard (unidentified).png", 66),
                        new AssetEntity("Stork marabou", "implement sticky methodologies", 4.95f, "stork marabou.fbx", "stork marabou.png", 50),
                        new AssetEntity("Cape clawless otter", "revolutionize vertical interfaces", 4.95f, "cape clawless otter.fbx", "cape clawless otter.png", 23),
                        new AssetEntity("Shrike southern white-crowned", "engineer world-class e-services", 9.95f, "shrike southern white-crowned.fbx", "shrike southern white-crowned.png", 22),
                        new AssetEntity("American crow", "engineer mission-critical eyeballs", 14.95f, "american crow.fbx", "american crow.png", 77),
                        new AssetEntity("Gray heron", "redefine magnetic models", 4.95f, "gray heron.fbx", "gray heron.png", 44),
                        new AssetEntity("Burrowing owl", "mesh integrated niches", 4.95f, "burrowing owl.fbx", "burrowing owl.png", 84),
                        new AssetEntity("Mudskipper (unidentified)", "generate best-of-breed interfaces", 4.95f, "mudskipper (unidentified).fbx", "mudskipper (unidentified).png", 56),
                        new AssetEntity("Peccary collared", "cultivate magnetic interfaces", 4.95f, "peccary collared.fbx", "peccary collared.png", 91),
                        new AssetEntity("Cattle egret", "streamline customized synergies", 9.95f, "cattle egret.fbx", "cattle egret.png", 72),
                        new AssetEntity("Arctic ground squirrel", "revolutionize robust mindshare", 9.95f, "arctic ground squirrel.fbx", "arctic ground squirrel.png", 79),
                        new AssetEntity("Sugar glider", "enhance rich partnerships", 4.95f, "sugar glider.fbx", "sugar glider.png", 41),
                        new AssetEntity("Turkey australian brush", "whiteboard proactive models", 14.95f, "turkey australian brush.fbx", "turkey australian brush.png", 18),
                        new AssetEntity("Secretary bird", "brand rich solutions", 4.95f, "secretary bird.fbx", "secretary bird.png", 86),
                        new AssetEntity("Brindled gnu", "incentivize plug-and-play action-items", 0f, "brindled gnu.fbx", "brindled gnu.png", 43),
                        new AssetEntity("Horned lark", "brand enterprise web services", 4.95f, "horned lark.fbx", "horned lark.png", 8),
                        new AssetEntity("Crow american", "deliver cross-media deliverables", 9.95f, "crow american.fbx", "crow american.png", 44),
                        new AssetEntity("White-browed sparrow weaver", "maximize transparent models", 14.95f, "white-browed sparrow weaver.fbx", "white-browed sparrow weaver.png", 96),
                        new AssetEntity("Camel dromedary", "target compelling deliverables", 0f, "camel dromedary.fbx", "camel dromedary.png", 73),
                        new AssetEntity("Lesser masked weaver", "disintermediate world-class bandwidth", 4.95f, "lesser masked weaver.fbx", "lesser masked weaver.png", 33),
                        new AssetEntity("White-winged black tern", "optimize web-enabled channels", 4.95f, "white-winged black tern.fbx", "white-winged black tern.png", 25),
                        new AssetEntity("Long-nosed bandicoot", "e-enable proactive mindshare", 14.95f, "long-nosed bandicoot.fbx", "long-nosed bandicoot.png", 77),
                        new AssetEntity("Cape starling", "strategize mission-critical users", 0f, "cape starling.fbx", "cape starling.png", 66),
                        new AssetEntity("African jacana", "harness scalable e-markets", 14.95f, "african jacana.fbx", "african jacana.png", 57),
                        new AssetEntity("Lizard mexican beaded", "transform cutting-edge interfaces", 14.95f, "lizard mexican beaded.fbx", "lizard mexican beaded.png", 17),
                        new AssetEntity("Mongoose eastern dwarf", "architect impactful schemas", 4.95f, "mongoose eastern dwarf.fbx", "mongoose eastern dwarf.png", 52),
                        new AssetEntity("Squirrel red", "recontextualize open-source technologies", 14.95f, "squirrel red.fbx", "squirrel red.png", 8),
                        new AssetEntity("Southern hairy-nosed wombat", "aggregate rich communities", 4.95f, "southern hairy-nosed wombat.fbx", "southern hairy-nosed wombat.png", 17),
                        new AssetEntity("Common rhea", "cultivate mission-critical solutions", 4.95f, "common rhea.fbx", "common rhea.png", 90),
                        new AssetEntity("Ringtail common", "architect 24/7 web services", 4.95f, "ringtail common.fbx", "ringtail common.png", 27),
                        new AssetEntity("Slender-billed cockatoo", "envisioneer virtual portals", 4.95f, "slender-billed cockatoo.fbx", "slender-billed cockatoo.png", 91),
                        new AssetEntity("Ostrich", "exploit granular eyeballs", 0f, "ostrich.fbx", "ostrich.png", 58),
                        new AssetEntity("Turkey australian brush", "syndicate best-of-breed web-readiness", 14.95f, "turkey australian brush.fbx", "turkey australian brush.png", 88),
                        new AssetEntity("Rose-ringed parakeet", "architect interactive infrastructures", 4.95f, "rose-ringed parakeet.fbx", "rose-ringed parakeet.png", 14),
                        new AssetEntity("Swan trumpeter", "disintermediate vertical supply-chains", 14.95f, "swan trumpeter.fbx", "swan trumpeter.png", 52)
                    });
                    break;
                case List<UserEntity> userList:
                    userList.AddRange(new List<UserEntity>()
                    {
                        new UserEntity("Herbacha", "Pierre-Marie", "A", "pma@ipme.com", "BJCNhdMU", "6 avenue des Pandas Roux", UserRole.Admin),
                        new UserEntity("Kentaro", "Sylvain", "G", "sg@ipme.com", "o2yZ5NQ4VE", "7 rue des Chats Miauleurs", UserRole.Admin),
                        new UserEntity("Alain", "Alain", "Terieur", "aterr@hotmail.com", "5x5LbU", "110 avenue des près", UserRole.Premium),
                        new UserEntity("DaFlash", "Barry", "Badlen", "bbadlen@csi.ccpd.gov", "126kWnXiR4234", "1 avenue des bolides", UserRole.Premium),
                        new UserEntity("Kiki", "Carl", "Ikki", "carliki@hotmail.com", "6kWnXiR42", "3 chemin du Kernel", UserRole.Basic),
                        new UserEntity("mdruhan0","Mamie","Druhan","mdruhan0@surveymonkey.com","fjJVnvFtCPfa","399 Knutson Terrace",UserRole.Basic),
                        new UserEntity("cgarvill1","Claudie","Garvill","cgarvill1@delicious.com","pbWzwlYNSxi","5396 Grim Crossing",UserRole.Premium),
                        new UserEntity("odonlon2","Ophelie","Donlon","odonlon2@harvard.edu","i5TBPreICs","35329 Marquette Parkway",UserRole.Premium),
                        new UserEntity("cturbefield3","Cesar","Turbefield","cturbefield3@1und1.de","vHyrrpn7Z","5 Westport Park",UserRole.Basic),
                        new UserEntity("irusted4","Isa","Rusted","irusted4@indiegogo.com","0U0UDP","9783 Rockefeller Trail",UserRole.Basic),
                        new UserEntity("afrenzel5","Alvina","Frenzel;","afrenzel5@zimbio.com","n01ATIOKwZ","19 Pierstorff Lane",UserRole.Premium),
                        new UserEntity("jkennan6","Jamil","Kennan","jkennan6@moonfruit.com","5x5LbU","136 Kinsman Road",UserRole.Premium),
                        new UserEntity("clivingstone7","Chickie","Livingstone","clivingstone7@purevolume.com","i7Xvfn","266 Roth Crossing",UserRole.Premium),
                        new UserEntity("dgimber8","Delinda","Gimber","dgimber8@nationalgeographic.com","BJCNhdMU","22 Bluestem Crossing",UserRole.Premium),
                        new UserEntity("sforgan9","Sasha","Forgan","sforgan9@alibaba.com","acmfgJpje","25081 Maple Wood Junction",UserRole.Basic),
                        new UserEntity("agorlera","Arda","Gorler","agorlera@nytimes.com","o2yZ5NQ4VE","50 Golf Hill",UserRole.Basic),
                        new UserEntity("sgongb","Stanwood","Gong","sgongb@whitehouse.gov","xs19ZxhOrnA","084 Southridge Way",UserRole.Basic),
                        new UserEntity("alalondec","Ashlan","Lalonde","alalondec@japanpost.jp","6kWnXiR42","9328 Lakeland Circle",UserRole.Basic),
                        new UserEntity("jriglesfordd","Jessamyn","Riglesford","jriglesfordd@netvibes.com","py6MoZqWjQrs","6 Riverside Lane",UserRole.Basic),
                        new UserEntity("dpenticoste","Darcy","Penticost","dpenticoste@desdev.cn","wnIs0CocU8","9818 Westport Terrace",UserRole.Premium),
                        new UserEntity("pwaghornf","Petronilla","Waghorn","pwaghornf@sitemeter.com","I5fFtiHKYlyN","9 Hazelcrest Drive",UserRole.Premium),
                        new UserEntity("kdudingg","Krystal","Duding","kdudingg@home.pl","briTFcX","9968 Graceland Park",UserRole.Basic),
                        new UserEntity("cmullinerh","Cornell","Mulliner","cmullinerh@businesswire.com","VgT4Cd0xhQfG","1 Pond Junction",UserRole.Basic),
                        new UserEntity("fsaulteri","Fae","Saulter","fsaulteri@cisco.com","PW26Io67iTE","9 East Court",UserRole.Basic),
                        new UserEntity("fdahlborgj","Forrest","Dahlborg","fdahlborgj@hubpages.com","mJ6g4OBK","3992 Gateway Pass",UserRole.Basic),
                        new UserEntity("tmerringtonk","Terrell","Merrington","tmerringtonk@amazon.com","ZNyUOD","58774 Claremont Point",UserRole.Premium),
                        new UserEntity("sdigginl","Salim","Diggin","sdigginl@ycombinator.com","ogk3E5","95569 Mifflin Junction",UserRole.Premium),
                        new UserEntity("wcollatonm","Waylen","Collaton","wcollatonm@tuttocitta.it","D3ICgf0Esy","230 Londonderry Point",UserRole.Basic),
                        new UserEntity("mveeln","Melvin","Veel","mveeln@sohu.com","WB9krQVmlC","8291 Lawn Park",UserRole.Premium),
                        new UserEntity("hcudmoreo","Hinze","Cudmore","hcudmoreo@weather.com","AHkzoLV","97 Almo Place",UserRole.Premium),
                        new UserEntity("cbaronp","Christiane","Baron","cbaronp@friendfeed.com","ZMpiqZP7","01 Glacier Hill Parkway",UserRole.Premium),
                        new UserEntity("bwoodwardq","Blinni","Woodward","bwoodwardq@mit.edu","jQp5qODb","5 West Lane",UserRole.Basic),
                        new UserEntity("ctromanr","Care","Troman","ctromanr@cisco.com","zIzSVNl","8 Miller Trail",UserRole.Basic),
                        new UserEntity("amacentees","Arnoldo","MacEntee","amacentees@angelfire.com","Bs1zyte","1 Del Sol Trail",UserRole.Premium),
                        new UserEntity("amachent","Austin","Machen","amachent@i2i.jp","rFAc9AWqfop","34 Sugar Alley",UserRole.Basic),
                        new UserEntity("lfearnsu","Lexis","Fearns","lfearnsu@e-recht24.de","NGO1swJ4tXqh","97 Eagle Crest Junction",UserRole.Premium),
                        new UserEntity("lambrosiniv","Lucita","Ambrosini","lambrosiniv@disqus.com","YeEp8QSJeo3H","8658 Haas Hill",UserRole.Basic),
                        new UserEntity("swheatleyw","Saba","Wheatley","swheatleyw@xinhuanet.com","xZuKsQxoBD7","18444 Roxbury Parkway",UserRole.Basic),
                        new UserEntity("rjeanesx","Russell","Jeanes","rjeanesx@redcross.org","DQDKMzK6q2Y","07890 Kedzie Park",UserRole.Premium),
                        new UserEntity("hpuxleyy","Humfried","Puxley","hpuxleyy@washington.edu","6XK9q990","5 Erie Court",UserRole.Premium),
                        new UserEntity("wleathardz","Wald","Leathard","wleathardz@youtube.com","mWNngcO","8 Lawn Street",UserRole.Basic),
                        new UserEntity("ljumel10","Lowe","Jumel","ljumel10@geocities.jp","7yblRldgOyE","5221 Manley Avenue",UserRole.Basic),
                        new UserEntity("tmaclaverty11","Trefor","MacLaverty","tmaclaverty11@upenn.edu","kIvbwQq0DSM","12355 Stone Corner Parkway",UserRole.Premium),
                        new UserEntity("mdancey12","Martyn","Dancey","mdancey12@miibeian.gov.cn","3ud0xstatCX2","656 Tennessee Alley",UserRole.Basic),
                        new UserEntity("obonson13","Odelinda","Bonson","obonson13@weather.com","URzQ3MA4ViuL","42 Orin Lane",UserRole.Premium),
                        new UserEntity("ehabeshaw14","Evelin","Habeshaw","ehabeshaw14@blogs.com","DgY0SY","70331 Drewry Center",UserRole.Premium),
                        new UserEntity("zpossa15","Zach","Possa","zpossa15@quantcast.com","xZ0az5WdL","931 Kedzie Place",UserRole.Basic),
                        new UserEntity("spursey16","Siegfried","Pursey","spursey16@cdc.gov","tJTq70EYU8y3","19583 Moland Alley",UserRole.Basic),
                        new UserEntity("daubury17","Dorothy","Aubury","daubury17@alexa.com","rDWEfeBwpYL","703 Thierer Trail",UserRole.Basic),
                        new UserEntity("ggourley18","Gallard","Gourley","ggourley18@rediff.com","jl60KOev","0392 Rockefeller Avenue",UserRole.Basic),
                        new UserEntity("iwalworche19","Iorgos","Walworche","iwalworche19@loc.gov","0mKQBNV","47 Maywood Avenue",UserRole.Basic),
                        new UserEntity("dsandom1a","Desmund","Sandom","dsandom1a@google.cn","M7fLqZeJH6c6","12 Havey Junction",UserRole.Basic),
                        new UserEntity("rwhetton1b","Randi","Whetton","rwhetton1b@facebook.com","m6bXJ4","915 Thackeray Circle",UserRole.Basic),
                        new UserEntity("apawle1c","Alfi","Pawle","apawle1c@tumblr.com","az3LwF","6015 Vera Point",UserRole.Basic),
                        new UserEntity("jallsup1d","Janaya","Allsup","jallsup1d@geocities.jp","dkNzUPdn93ko","432 Monument Parkway",UserRole.Basic),
                        new UserEntity("tculy1e","Tucker","Culy","tculy1e@vkontakte.ru","CH9v76q","25363 Lukken Lane",UserRole.Basic),
                        new UserEntity("agerriet1f","Artur","Gerriet","agerriet1f@google.de","niBaqDmKGct","3347 Petterle Trail",UserRole.Premium),
                        new UserEntity("esweetmore1g","Emmy","Sweetmore","esweetmore1g@nyu.edu","0Uk5R4QZo","1 Dexter Center",UserRole.Premium),
                        new UserEntity("sshadwick1h","Stevana","Shadwick","sshadwick1h@wix.com","zyW4V5G","4965 Thierer Court",UserRole.Premium),
                        new UserEntity("eerickssen1i","Elsworth","Erickssen","eerickssen1i@newyorker.com","JMmzwSo","78030 Park Meadow Street",UserRole.Basic),
                        new UserEntity("cescalante1j","Cheslie","Escalante","cescalante1j@hostgator.com","hbiC0yqVn","21 Oak Valley Terrace",UserRole.Basic),
                        new UserEntity("abester1k","Alasteir","Bester","abester1k@msn.com","aqLZlAmUeHHe","9 Stuart Road",UserRole.Basic),
                        new UserEntity("poubridge1l","Pearline","Oubridge","poubridge1l@nationalgeographic.com","mAj5jjm","9286 Spohn Center",UserRole.Premium),
                        new UserEntity("jcurling1m","Jeffy","Curling","jcurling1m@vistaprint.com","OdTefgaUI0Eb","49 Monica Point",UserRole.Premium),
                        new UserEntity("awilce1n","Andres","Wilce","awilce1n@nature.com","SfdkA7wuzK9","2703 Crescent Oaks Circle",UserRole.Basic),
                        new UserEntity("bjedraszek1o","Brande","Jedraszek","bjedraszek1o@marriott.com","MYRq0O","428 Loeprich Junction",UserRole.Basic),
                        new UserEntity("fgraveson1p","Frazier","Graveson","fgraveson1p@cnbc.com","bhqBEu","47368 Parkside Center",UserRole.Premium),
                        new UserEntity("laskham1q","Lee","Askham","laskham1q@dropbox.com","EpmZ72pDvo1","37 Becker Park",UserRole.Premium),
                        new UserEntity("xnollet1r","Xenia","Nollet","xnollet1r@ucoz.ru","LkEGTkBCZ","26706 Ridgeview Avenue",UserRole.Premium),
                        new UserEntity("soscroft1s","Steffen","Oscroft","soscroft1s@reuters.com","i94H8OFhK","68 Delladonna Circle",UserRole.Premium),
                        new UserEntity("hmanuelli1t","Hermione","Manuelli","hmanuelli1t@squarespace.com","oSAL8EO","1085 Butterfield Court",UserRole.Premium),
                        new UserEntity("dklesel1u","Donny","Klesel","dklesel1u@un.org","4MwZueZ6","53944 Forest Junction",UserRole.Basic),
                        new UserEntity("mbatalini1v","Morgan","Batalini","mbatalini1v@nbcnews.com","RXRG0FR912U","685 Monica Point",UserRole.Premium),
                        new UserEntity("mtrembath1w","Miof mela","Trembath","mtrembath1w@de.vu","iPZ0JOdbX","51 Fulton Junction",UserRole.Premium),
                        new UserEntity("edolby1x","Elsie","Dolby","edolby1x@ycombinator.com","mdoVDh4","87 Schiller Court",UserRole.Premium),
                        new UserEntity("ctopling1y","Clayborn","Topling","ctopling1y@icio.us","gv82ZLPpN","87187 Heffernan Plaza",UserRole.Basic),
                        new UserEntity("abenoey1z","Analise","Benoey","abenoey1z@shutterfly.com","35183m6VAV","4 Kim Court",UserRole.Premium),
                        new UserEntity("dfurmage20","Dennie","Furmage","dfurmage20@whitehouse.gov","ha5ItsJCfx8","4 Fallview Point",UserRole.Premium),
                        new UserEntity("cspare21","Carver","Spare","cspare21@nbcnews.com","N5QZPJHmw7SW","6697 Ronald Regan Trail",UserRole.Basic),
                        new UserEntity("kjeffrey22","Kandy","Jeffrey","kjeffrey22@economist.com","oy8CLyVq","979 Morrow Trail",UserRole.Basic),
                        new UserEntity("lduck23","Lois","Duck","lduck23@youtube.com","1tXqjGY","842 Memorial Circle",UserRole.Premium),
                        new UserEntity("kdiangelo24","Kore","Di Angelo","kdiangelo24@sfgate.com","x4qvIm7l","5326 Tennyson Point",UserRole.Premium),
                        new UserEntity("warnholtz25","William","Arnholtz","warnholtz25@cisco.com","FSFwwhdpm","5191 Cambridge Pass",UserRole.Basic),
                        new UserEntity("qwelsby26","Quint","Welsby","qwelsby26@tripod.com","WrVUfWnin","00296 Logan Alley",UserRole.Basic),
                        new UserEntity("sbeardon27","Sadella","Beardon","sbeardon27@shinystat.com","54NEHWx","40 Portage Court",UserRole.Basic),
                        new UserEntity("gpotter28","Gardener","Potter","gpotter28@army.mil","z9I9S0","349 Bartelt Center",UserRole.Premium),
                        new UserEntity("smcnysche29","Silvester","McNysche","smcnysche29@gov.uk","6cIGk7kOzgkV","9052 Crownhardt Parkway",UserRole.Premium),
                        new UserEntity("lshave2a","Lorrie","Shave","lshave2a@census.gov","zMZfauzDI12c","940 Dixon Pass",UserRole.Premium),
                        new UserEntity("fsprason2b","Finlay","Sprason","fsprason2b@google.it","jJkz8pnX3E","0657 Red Cloud Avenue",UserRole.Basic),
                        new UserEntity("rgaddas2c","Renee","Gaddas","rgaddas2c@slate.com","m50NLOhg","83742 Old Gate Lane",UserRole.Premium),
                        new UserEntity("dstanman2d","Diena","Stanman","dstanman2d@imageshack.us","JFh07cO","89565 Northwestern Point",UserRole.Basic),
                        new UserEntity("lhylden2e","Lorant","Hylden","lhylden2e@psu.edu","SWYK0W","90 Fieldstone Plaza",UserRole.Premium),
                        new UserEntity("ffogg2f","Fair","Fogg","ffogg2f@symantec.com","BVzOoWx7","6 Coolidge Junction",UserRole.Basic),
                        new UserEntity("dcopins2g","Darby","Copins","dcopins2g@a8.net","nRAlRDJ4or","95 Sloan Terrace",UserRole.Premium),
                        new UserEntity("smuselli2h","Stephanus","Muselli","smuselli2h@npr.org","i0uUGAfWm4I","3348 Pennsylvania Plaza",UserRole.Premium),
                        new UserEntity("jcaughtry2i","Jeannie","Caughtry","jcaughtry2i@furl.net","Uv0oLLYK","430 Toban Road",UserRole.Premium),
                        new UserEntity("clintin2j","Carmelita","Lintin","clintin2j@youku.com","IprvQV9ePRj","54 Nova Hill",UserRole.Premium),
                        new UserEntity("tliddiatt2k","Tatiania","Liddiatt","tliddiatt2k@ed.gov","IYQCVaiHU","09 Jenifer Junction",UserRole.Premium),
                        new UserEntity("kwolfers2l","Kandace","Wolfers","kwolfers2l@globo.com","XYxH8M4k","53631 Mesta Avenue",UserRole.Premium),
                        new UserEntity("mdevo2m","Marney","Devo","mdevo2m@moonfruit.com","gSHxZgFqV","720 Fordem Alley",UserRole.Basic),
                        new UserEntity("mpooke2n","Marlyn","Pooke","mpooke2n@nhs.uk","QZRksosX9","740 Eagle Crest Park",UserRole.Basic),
                        new UserEntity("kpaulack2o","Katherina","Paulack","kpaulack2o@dell.com","mkaxj6Bd","65 Moose Place",UserRole.Basic),
                        new UserEntity("jcave2p","Jsandye","Cave","jcave2p@privacy.gov.au","P8p1ab","97477 Pawling Alley",UserRole.Basic),
                        new UserEntity("strelevan2q","Salomon","Trelevan","strelevan2q@domainmarket.com","ql5dyT1z6b","9 Sunbrook Hill",UserRole.Premium),
                        new UserEntity("ttwycross2r","Turner","Twycross","ttwycross2r@cargocollective.com","Sb65kZ1h7","981 Moose Circle",UserRole.Premium)
                    });
                    break;
                case List<OrderEntity> orderList:
                    orderList.AddRange(new List<OrderEntity>()
                    {
                        new OrderEntity(new DateTime(2022, 01, 11), 95),
                        new OrderEntity(new DateTime(2022, 02, 02), 97),
                        new OrderEntity(new DateTime(2021, 12, 18), 11),
                        new OrderEntity(new DateTime(2022, 02, 01), 76),
                        new OrderEntity(new DateTime(2021, 12, 16), 3),
                        new OrderEntity(new DateTime(2022, 02, 07), 93),
                        new OrderEntity(new DateTime(2021, 12, 29), 23),
                        new OrderEntity(new DateTime(2022, 02, 13), 67),
                        new OrderEntity(new DateTime(2022, 02, 11), 46),
                        new OrderEntity(new DateTime(2022, 01, 24), 50),
                        new OrderEntity(new DateTime(2021, 12, 09), 73),
                        new OrderEntity(new DateTime(2021, 12, 28), 90),
                        new OrderEntity(new DateTime(2022, 02, 11), 14),
                        new OrderEntity(new DateTime(2022, 01, 07), 32),
                        new OrderEntity(new DateTime(2022, 02, 05), 7),
                        new OrderEntity(new DateTime(2022, 01, 27), 48),
                        new OrderEntity(new DateTime(2022, 02, 14), 72),
                        new OrderEntity(new DateTime(2022, 01, 14), 97),
                        new OrderEntity(new DateTime(2022, 02, 03), 64),
                        new OrderEntity(new DateTime(2022, 02, 14), 24),
                        new OrderEntity(new DateTime(2022, 02, 16), 46),
                        new OrderEntity(new DateTime(2022, 01, 20), 19),
                        new OrderEntity(new DateTime(2021, 12, 08), 92),
                        new OrderEntity(new DateTime(2022, 02, 03), 6),
                        new OrderEntity(new DateTime(2022, 01, 15), 28),
                        new OrderEntity(new DateTime(2022, 01, 15), 60),
                        new OrderEntity(new DateTime(2022, 02, 19), 82),
                        new OrderEntity(new DateTime(2022, 01, 27), 42),
                        new OrderEntity(new DateTime(2022, 01, 31), 12)
                    });
                    break;
                case List<PurchaseEntity> purchaseList:
                    purchaseList.AddRange(new List<PurchaseEntity>()
                    {
                        new PurchaseEntity(1,false,4.95f,2),
                        new PurchaseEntity(2,false,4.95f,37),
                        new PurchaseEntity(3,false,4.95f,36),
                        new PurchaseEntity(4,false,4.95f,41),
                        new PurchaseEntity(4,true,4.95f,5),
                        new PurchaseEntity(5,false,4.95f,31),
                        new PurchaseEntity(5,true,4.95f,43),
                        new PurchaseEntity(6,true,4.95f,8),
                        new PurchaseEntity(6,true,4.95f,22),
                        new PurchaseEntity(6,true,4.95f,28),
                        new PurchaseEntity(6,true,4.95f,42),
                        new PurchaseEntity(7,true,4.95f,8),
                        new PurchaseEntity(8,true,4.95f,45),
                        new PurchaseEntity(9,false,4.95f,12),
                        new PurchaseEntity(10,false,4.95f,3),
                        new PurchaseEntity(11,false,4.95f,41),
                        new PurchaseEntity(12,true,4.95f,32),
                        new PurchaseEntity(13,false,4.95f,14),
                        new PurchaseEntity(13,true,4.95f,50),
                        new PurchaseEntity(13,true,4.95f,35),
                        new PurchaseEntity(14,true,4.95f,16),
                        new PurchaseEntity(15,false,4.95f,25),
                        new PurchaseEntity(16,true,4.95f,31),
                        new PurchaseEntity(17,false,4.95f,20),
                        new PurchaseEntity(18,false,4.95f,43),
                        new PurchaseEntity(19,false,4.95f,38),
                        new PurchaseEntity(20,false,4.95f,11),
                        new PurchaseEntity(20,true,4.95f,17),
                        new PurchaseEntity(21,true,4.95f,8),
                        new PurchaseEntity(22,false,4.95f,23),
                        new PurchaseEntity(23,true,4.95f,22),
                        new PurchaseEntity(24,false,4.95f,39),
                        new PurchaseEntity(25,false,4.95f,46),
                        new PurchaseEntity(26,true,4.95f,27),
                        new PurchaseEntity(27,false,4.95f,20),
                        new PurchaseEntity(28,true,4.95f,38),
                        new PurchaseEntity(29,false,4.95f,12),
                        new PurchaseEntity(29,false,4.95f,46),
                        new PurchaseEntity(29,true,4.95f,15)
                    });
                    break;
                case List<ReviewEntity> purchaseList:
                    purchaseList.AddRange(new List<ReviewEntity>()
                    {
                        new ReviewEntity(3,"Laceration of muscle, fascia and tendon of long head of biceps, left arm, initial encounter",true,2,95),
                        new ReviewEntity(3,"Bent bone of right ulna, subsequent encounter for closed fracture with malunion",true,37,97),
                        new ReviewEntity(5,"Radial collateral ligament sprain of unspecified elbow, sequela",false,36,11),
                        new ReviewEntity(2,"Open bite, unspecified thigh, initial encounter",false,41,76),
                        new ReviewEntity(1,"Obesity complicating pregnancy, first trimester",true,5,76),
                        new ReviewEntity(4,"Injury of ulnar nerve at forearm level, left arm",true,31,3),
                        new ReviewEntity(4,"Dislocation of distal interphalangeal joint of right index finger, subsequent encounter",false,43,3),
                        new ReviewEntity(3,"Puncture wound without foreign body, right lower leg, sequela",false,8,93),
                        new ReviewEntity(3,"Legal intervention involving injury by machine gun, law enforcement official injured, subsequent encounter",false,22,93),
                        new ReviewEntity(4,"Fatigue fracture of vertebra, lumbar region",false,28,93),
                        new ReviewEntity(2,"Other calcification of muscle, unspecified shoulder",false,42,93),
                        new ReviewEntity(5,"Giant cell granuloma, central",false,8,23),
                        new ReviewEntity(2,"Hydrocephalus in diseases classified elsewhere",false,45,67),
                        new ReviewEntity(1,"Contact with hay derrick, initial encounter",false,12,46),
                        new ReviewEntity(2,"Laceration without foreign body of unspecified breast, sequela",false,3,50),
                        new ReviewEntity(1,"Nondisplaced segmental fracture of shaft of right tibia, subsequent encounter for closed fracture with malunion",false,41,73),
                        new ReviewEntity(4,"Blood alcohol level of 60-79 mg/100 ml",false,32,90),
                        new ReviewEntity(5,"Open bite of abdominal wall, unspecified quadrant without penetration into peritoneal cavity",false,14,14),
                        new ReviewEntity(2,"Poisoning by other antiprotozoal drugs, accidental (unintentional)",false,50,14),
                        new ReviewEntity(1,"Other injury of adrenal gland, initial encounter",false,35,14),
                        new ReviewEntity(3,"Burn of first degree of unspecified palm, initial encounter",false,16,32),
                        new ReviewEntity(2,"Unspecified superficial injury of unspecified part of head",false,25,7),
                        new ReviewEntity(2,"Congenital occlusion of ureter, unspecified",false,31,48),
                        new ReviewEntity(5,"Other specified injury of unspecified blood vessel at lower leg level, unspecified leg, sequela",false,20,72),
                        new ReviewEntity(4,"Cerebral infarction due to thrombosis of right carotid artery",false,43,97),
                        new ReviewEntity(4,"Spondylopathy in diseases classified elsewhere, occipito-atlanto-axial region",false,38,64),
                        new ReviewEntity(3,"Unspecified fracture of unspecified patella",false,11,24),
                        new ReviewEntity(1,"Nondisplaced fracture of neck of right radius, initial encounter for closed fracture",false,17,24),
                        new ReviewEntity(4,"Injury of digital nerve of other finger, sequela",false,8,46),
                        new ReviewEntity(5,"Subluxation of left ankle joint, initial encounter",false,23,19),
                        new ReviewEntity(5,"Unspecified pedal cyclist injured in collision with fixed or stationary object in nontraffic accident",false,22,92),
                        new ReviewEntity(5,"Immersion hand, unspecified hand, subsequent encounter",false,39,6),
                        new ReviewEntity(2,"Non-follicular (diffuse) lymphoma, unspecified, unspecified site",false,46,28),
                        new ReviewEntity(1,"Other diseases of capillaries",false,27,60),
                        new ReviewEntity(2,"Pulmonary histoplasmosis capsulati, unspecified",false,20,82),
                        new ReviewEntity(5,"Displaced segmental fracture of shaft of radius, right arm",false,38,42),
                        new ReviewEntity(1,"Unspecified open wound of right thumb with damage to nail, subsequent encounter",false,12,12)
                    });
                    break;
                default:
                    throw new DataTypeNotSupportedException("No dummy data for this Type of Data.");
            }
        }

        public void SaveData(List<T> listToSave)
        {
            throw new SaveNotSupportedException("Dummy Data Handler doesn't support saving.");
        }
    }
}
