//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//
//     Les changements apportés à ce fichier peuvent provoquer un comportement incorrect et seront perdus si
//     le code est regénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AssetDto", Namespace="http://schemas.datacontract.org/2004/07/Fantastic3D.Legacy.Dtos")]
    public partial class AssetDto : object
    {
        
        private int IdField;
        
        private string NameField;
        
        private string _creatorField;
        
        private string _descriptionField;
        
        private float _priceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _creator
        {
            get
            {
                return this._creatorField;
            }
            set
            {
                this._creatorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string _description
        {
            get
            {
                return this._descriptionField;
            }
            set
            {
                this._descriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public float _price
        {
            get
            {
                return this._priceField;
            }
            set
            {
                this._priceField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IAssetService")]
    public interface IAssetService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssetService/GetList", ReplyAction="http://tempuri.org/IAssetService/GetListResponse")]
        System.Threading.Tasks.Task<string[]> GetListAsync(int offset);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssetService/SearchAssetDto", ReplyAction="http://tempuri.org/IAssetService/SearchAssetDtoResponse")]
        System.Threading.Tasks.Task<ServiceReference1.AssetDto> SearchAssetDtoAsync(string modelName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAssetService/GetAssetDto", ReplyAction="http://tempuri.org/IAssetService/GetAssetDtoResponse")]
        System.Threading.Tasks.Task<ServiceReference1.AssetDto> GetAssetDtoAsync(int modelId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IAssetServiceChannel : ServiceReference1.IAssetService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class AssetServiceClient : System.ServiceModel.ClientBase<ServiceReference1.IAssetService>, ServiceReference1.IAssetService
    {
        
        /// <summary>
        /// Implémentez cette méthode partielle pour configurer le point de terminaison de service.
        /// </summary>
        /// <param name="serviceEndpoint">Point de terminaison à configurer</param>
        /// <param name="clientCredentials">Informations d'identification du client</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public AssetServiceClient() : 
                base(AssetServiceClient.GetDefaultBinding(), AssetServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IAssetService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AssetServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(AssetServiceClient.GetBindingForEndpoint(endpointConfiguration), AssetServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AssetServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(AssetServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AssetServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(AssetServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AssetServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string[]> GetListAsync(int offset)
        {
            return base.Channel.GetListAsync(offset);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.AssetDto> SearchAssetDtoAsync(string modelName)
        {
            return base.Channel.SearchAssetDtoAsync(modelName);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.AssetDto> GetAssetDtoAsync(int modelId)
        {
            return base.Channel.GetAssetDtoAsync(modelId);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IAssetService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Le point de terminaison nommé \'{0}\' est introuvable.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IAssetService))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:55966/F3DAssetService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Le point de terminaison nommé \'{0}\' est introuvable.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return AssetServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IAssetService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return AssetServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IAssetService);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IAssetService,
        }
    }
}
